export const local = {
        colors: {
            primary: {
                '950': 'rgb(var(--color-primary-950) / <alpha-value>)',
                '900': 'rgb(var(--color-primary-900) / <alpha-value>)',
                '800': 'rgb(var(--color-primary-800) / <alpha-value>)',
                '700': 'rgb(var(--color-primary-700) / <alpha-value>)',
                '600': 'rgb(var(--color-primary-600) / <alpha-value>)',
                '500': 'rgb(var(--color-primary-500) / <alpha-value>)',
                '400': 'rgb(var(--color-primary-400) / <alpha-value>)',
                '300': 'rgb(var(--color-primary-300) / <alpha-value>)',
                '200': 'rgb(var(--color-primary-200) / <alpha-value>)',
                '100': 'rgb(var(--color-primary-100) / <alpha-value>)',
                '50': 'rgb(var(--color-primary-50) / <alpha-value>)',
                DEFAULT: 'rgb(var(--color-primary-500) / <alpha-value>)',
            },
            secondary: {
                '950': 'rgb(var(--color-secondary-950) / <alpha-value>)',
                '900': 'rgb(var(--color-secondary-900) / <alpha-value>)',
                '800': 'rgb(var(--color-secondary-800) / <alpha-value>)',
                '700': 'rgb(var(--color-secondary-700) / <alpha-value>)',
                '600': 'rgb(var(--color-secondary-600) / <alpha-value>)',
                '500': 'rgb(var(--color-secondary-500) / <alpha-value>)',
                '400': 'rgb(var(--color-secondary-400) / <alpha-value>)',
                '300': 'rgb(var(--color-secondary-300) / <alpha-value>)',
                '200': 'rgb(var(--color-secondary-200) / <alpha-value>)',
                '100': 'rgb(var(--color-secondary-100) / <alpha-value>)',
                '50': 'rgb(var(--color-secondary-50) / <alpha-value>)',
                DEFAULT: 'rgb(var(--color-secondary-500) / <alpha-value>)',
            },
            error: {
                '950': 'rgb(var(--color-error-950) / <alpha-value>)',
                '900': 'rgb(var(--color-error-900) / <alpha-value>)',
                '800': 'rgb(var(--color-error-800) / <alpha-value>)',
                '700': 'rgb(var(--color-error-700) / <alpha-value>)',
                '600': 'rgb(var(--color-error-600) / <alpha-value>)',
                '500': 'rgb(var(--color-error-500) / <alpha-value>)',
                '400': 'rgb(var(--color-error-400) / <alpha-value>)',
                '300': 'rgb(var(--color-error-300) / <alpha-value>)',
                '200': 'rgb(var(--color-error-200) / <alpha-value>)',
                '100': 'rgb(var(--color-error-100) / <alpha-value>)',
                '50': 'rgb(var(--color-error-50) / <alpha-value>)',
                DEFAULT: 'rgb(var(--color-error-500) / <alpha-value>)',
            },
            gray: {
                '950': 'rgb(var(--color-gray-950) / <alpha-value>)',
                '900': 'rgb(var(--color-gray-900) / <alpha-value>)',
                '800': 'rgb(var(--color-gray-800) / <alpha-value>)',
                '700': 'rgb(var(--color-gray-700) / <alpha-value>)',
                '600': 'rgb(var(--color-gray-600) / <alpha-value>)',
                '500': 'rgb(var(--color-gray-500) / <alpha-value>)',
                '400': 'rgb(var(--color-gray-400) / <alpha-value>)',
                '300': 'rgb(var(--color-gray-300) / <alpha-value>)',
                '200': 'rgb(var(--color-gray-200) / <alpha-value>)',
                '100': 'rgb(var(--color-gray-100) / <alpha-value>)',
                '50': 'rgb(var(--color-gray-50) / <alpha-value>)',
                DEFAULT: 'rgb(var(--color-gray-500) / <alpha-value>)',
            }
        }
}